# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true    Removed cause Github

# Setup
title:               AlexJP
tagline:             'The gentleman developer'
description:         'Web development, refined. <a href="https://twitter.com/ajp529" target="_blank">@ajp529</a>.'
url:                 'http://www.alexjp.com'
baseurl:             
paginate:            3

# About/contact
author:
  name:              Alex Pedersen
  url:               https://twitter.com/ajp529
  email:             Alex@AlexJP.com

# Custom vars
version:             1.0.1
