# My variables
name: Alex Pedersen
description: Passionate technology professional
google_verification: null

url:                 'http://www.alexjp.com'


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
