# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               AlexJP
tagline:             'The gentleman developer'
description:         'Web development, refined. <a href="https://twitter.com/ajp529" target="_blank">@ajp529</a>.'
url:                 'https://alexjp.com'
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Alex Pedersen
  url:               https://twitter.com/ajp529
  email:             Alex@AlexJP.com

# Custom vars
version:             1.0.0
